import main as main_file 
main_file.create("Avinash",25)
main_file.create("src",70,3600) 
main_file.read("Avinash")
main_file.read("src")
main_file.create("Avinash",50)
main_file.modify("Avinash",55)
main_file.delete("Avinash")
th1=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
th1.start()
th1.sleep()
th2=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
th2.start()
th2.sleep()
